# Makefile para el firmware en ASM del procesador erc2-v

# --- Configuración del Compilador ---
CROSS_COMPILE ?= riscv64-unknown-elf-

# El nombre del binario final
TARGET      = test_sp

# Herramientas
CC = $(CROSS_COMPILE)gcc
OBJCOPY = $(CROSS_COMPILE)objcopy

# --- Ficheros Fuente ---
SOURCES = $(TARGET).S
OBJS = $(TARGET).o

# --- Opciones de Compilación ---
CFLAGS = -march=rv32i -mabi=ilp32 -O2 -g -nostdlib -Tlinker.ld

# --- Reglas del Makefile ---
.PHONY: all clean

# El objetivo por defecto es construir el fichero .hex
all: $(TARGET).hex

# Regla para convertir el binario a formato Verilog HEX limpio
$(TARGET).hex: $(TARGET).bin
	./bin_to_hex.py $^ $@

# Regla para extraer el binario raw del fichero ELF
$(TARGET).bin: $(TARGET).elf
	$(OBJCOPY) -O binary $^ $@

# Regla para enlazar los objetos y crear el ELF final
$(TARGET).elf: $(OBJS)
	$(CC) $(CFLAGS) -o $@ $(OBJS)

# Reglas genéricas para compilar/ensamblar
%.o: %.S
	$(CC) $(CFLAGS) -c -o $@ $<

# Objetivo para limpiar los ficheros generados
clean:
	rm -f $(TARGET).o $(TARGET).elf $(TARGET).bin $(TARGET).hex
